from .test_bool import TestBool
from .test_complex import TestComplex
from .test_dict import TestDict
from .test_float import TestFloat
from .test_integer import TestInteger
from .test_list import TestList
from .test_set import TestSet
from .test_string import TestString
from .test_tuple import TestTuple
